### ISSUE TITLE
ERRO - Warming up the cache.

### ISSUE THREAD

**Issue by vinii8817** [mhubig/docker-partkeepr#10]
Thank you so much for sharing your work. ;-)

I have a problem at the end of the installation process.

There is not much information about the error, it is attached.
Can you help me with this?

My System config:
Docker version 18.03.1-ce, build 9ee9f40
MacOSX 10.13.6 High Sierra

![screenshot 2018-07-15 22 42 45](https://user-images.githubusercontent.com/20617848/42740750-cee5b29a-8881-11e8-9b32-5621d6588a7b.png)

**Comment by mhubig** [comment]
Maybe this is the same problem as reported in #9? Can you please try to increase the `max_execution_time` in `php.ini`?

**Comment by jn-simonnet** [comment]
Yes indeed, I have increased the max_execution_time :-)
My suggestion was to change the php.ini which comes with the container in order to avoid the issue entirely.

**Comment by vinii8817** [comment]
Sorry for the delay, yes, this is resolved my case.
Thanks your time.

**Comment by terxw** [comment]
Hi, after increasing max_execution_time the problem persist
latest images as of this writing, max_execution_time = 180
hangs on last setup step 2/2 with error - warming up the cache - invalid response from server
